### ISSUE TITLE
create existing resource does not store aws_resource_id

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-awssdk-plugin#101]
Run a blueprint with such node template:
```yaml
  vpc:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      client_config: *client_config
      use_external_resource: true
      resource_id: { get_input: vpc_id }
      resource_config:
        kwargs:
          CidrBlock: 'N/A'
```

After it is created look at the node instance:

```shell
  ::  cfy node-inst get vpc_zap1hf
Retrieving node instance vpc_zap1hf

Node-instance:
+------------+---------------+---------+---------+---------+--------------+----------------+------------+
|     id     | deployment_id | host_id | node_id |  state  | availability |  tenant_name   | created_by |
+------------+---------------+---------+---------+---------+--------------+----------------+------------+
| vpc_zap1hf | new_template0 |         |   vpc   | started |    tenant    | default_tenant |   admin    |
+------------+---------------+---------+---------+---------+--------------+----------------+------------+

Instance runtime properties:

```

The runtime properties are empty. These should be saved.
