### ISSUE TITLE
eni should look for relationships to security groups

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-awssdk-plugin#102]
Instead of the below:

```
  public_subnet_nic:
    type: cloudify.nodes.aws.ec2.Interface
    properties:
      client_config: *client_config
      resource_config:
        kwargs: {}
    relationships:
      - type: cloudify.relationships.depends_on
        target: public_subnet
      - type: cloudify.relationships.depends_on
        target: security_group
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          inputs:
            resource_config:
              SubnetId: { get_input: public_subnet_id }
              Groups:
              - { get_attribute: [ security_group, aws_resource_id ] }

  security_group:
    type: cloudify.nodes.aws.ec2.SecurityGroup
    properties:
      resource_config:
        kwargs:
          GroupName: ExampleSecurityGroup
          Description: Created by template-blueprint aws-blueprint.yaml.
          VpcId: { get_input: vpc_id }
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: vpc

```

We should be look for relationships to a target of type `cloudify.nodes.aws.ec2.SecurityGroup` add to the Groups list.
