### ISSUE TITLE
Multiple network interfaces in EC2 instance

### ISSUE THREAD

**Issue by rbk1001** [cloudify-incubator/cloudify-awssdk-plugin#115]
Hi

I followed cloudify-environment-setup-latest/aws.yaml and able to create EC2 instance within one interface. I need help on preparing the blueprint file for creating multiple interfaces in one EC2 instance.

Apprecicated if anyone can help on that.

**Comment by rbk1001** [comment]
tried to include two nics configuration in the blue print, but it is failed due to below reason. it looks like we cannot add more than one network interface in awssdk.

2018-03-29 08:07:53.948  CFY <cloudify-environment-setup-latest> [cloudify_host_gw6y9f.configure] Task failed 'cloudify_awssdk.ec2.resources.instances.create' -> An error occurred (InvalidParameterValue) when calling the RunInstances operation: Each network interface requires a unique device index.
2018-03-29 08:07:53.949  CFY <cloudify-environment-setup-latest> [ip2_5ncsjh.start] Sending task 'cloudify_awssdk.ec2.resources.elasticip.attach'

  cloudify_host:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      agent_config:
        install_method: none
      resource_config:
        kwargs:
          MinCount: 1
          MaxCount: 1
          ImageId: { get_input: ami }
          InstanceType: { get_input: instance_type }
          KeyName: { get_input: key_name }
          BlockDeviceMappings:
          - DeviceName: '/dev/sda1'
            Ebs:
              DeleteOnTermination: True
          Placement:
            AvailabilityZone: { get_input: availability_zone }
          UserData: { get_attribute: [ cloudify_host_cloud_config, cloud_config ] }
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.depends_on
        target: cloudify_host_cloud_config
      - type: cloudify.relationships.depends_on
        target: nic
      - type: cloudify.relationships.depends_on
        target: nic2
      - type: cloudify.relationships.depends_on
        target: pgwu_ami
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }

**Comment by EarthmanT** [comment]
Hi,

The way that you have presented it is supposed to work. I will look into it to see what is going on.

Another way to do this is like this:

```
  intermediate_nic_node:
    type: cloudify.nodes.Root
    relationships:
    - type: cloudify.relationships.depends_on
      target: nic
    - type: cloudify.relationships.depends_on
      target: nic1

  cloudify_host:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      agent_config:
        install_method: none
      resource_config:
        kwargs:
          MinCount: 1
          MaxCount: 1
          ImageId: { get_input: ami }
          InstanceType: { get_input: instance_type }
          BlockDeviceMappings:
          - DeviceName: '/dev/sda1'
            Ebs:
              DeleteOnTermination: True
          Placement:
            AvailabilityZone: { get_input: availability_zone }
          UserData: { get_attribute: [ cloudify_host_cloud_config, cloud_config ] }
          NetworkInterfaces:
          - DeviceIndex: 0
            NetworkInterfaceId: { get_attribute: [ nic, aws_resource_id ] }
          - DeviceIndex: 1
            NetworkInterfaceId: { get_attribute: [ nic1, aws_resource_id ] }
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.depends_on
        target: cloudify_host_cloud_config
      - type: cloudify.relationships.depends_on
        target: intermediate_nic_node
      # - type: cloudify.relationships.depends_on
      #   target: nic
      # - type: cloudify.relationships.depends_on
      #   target: nic1
      - type: cloudify.relationships.depends_on
        target: centos_core_ami              
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }

```

That's obviously not a great answer. We will fix it.

**Comment by rbk1001** [comment]
one question on the above setting. if I have 2 nic, I should have only one internet gateway or two?

**Comment by rbk1001** [comment]
I cannot really able to create the instance after using the syntax. is it possible for you to help on what is going wrong?

blueprint => https://pastebin.com/ZVrpkj3v
output => https://pastebin.com/UfeYaaNX

**Comment by EarthmanT** [comment]
Hi, what is the command that you are using to execute this install workflow? Are you using "task retries and task retry interval", like this?
```
$ cfy install cloudify-environment-setup-latest/aws.yaml -i cloudify-environment-setup-latest/inputs/aws.yaml --install-plugins --task-retries=30 --task-retry-interval=5
```
These flags are required when running in local (CLI only mode).

By the way, we have provided a fix for the multiple nics in #116, see [version 2.1.1](https://github.com/cloudify-incubator/cloudify-awssdk-plugin/releases/tag/2.1.1).

**Comment by rbk1001** [comment]
Hi 

yes. I use the above command with --install-plugins --task-retries=1 --task-retry-interval=5, any issue on this? please kindly correct me.

I see you have resolve the issue, but could you help to guide me how I can change it?

**Comment by EarthmanT** [comment]
In the execution log that you sent, it appears that the issue is that the nat gateway stays in pending too long. I would increase those retries to at least 15.

Multiple nics should now look like this:
```
  nic1:
    type: cloudify.nodes.aws.ec2.Interface
    properties:
      client_config: *client_config
      resource_config:
        kwargs:
          Description: Created by hello-world-blueprint aws-blueprint.yaml.
          SubnetId: { get_attribute: [ public_subnet, aws_resource_id] }
          Groups:
          - { get_attribute: [ security_group, aws_resource_id ] }
    relationships:
    - type: cloudify.relationships.depends_on
      target: public_subnet
    - type: cloudify.relationships.depends_on
      target: security_group
    - type: cloudify.relationships.depends_on
      target: security_group_rules
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }

  nic2:
    type: cloudify.nodes.aws.ec2.Interface
    properties:
      client_config: *client_config
      resource_config:
        kwargs:
          Description: Created by hello-world-blueprint aws-blueprint.yaml.
          SubnetId: { get_attribute: [ private_subnet, aws_resource_id] }
          Groups:
          - { get_attribute: [ security_group, aws_resource_id ] }
    relationships:
    - type: cloudify.relationships.depends_on
      target: private_subnet
    - type: cloudify.relationships.depends_on
      target: security_group
    - type: cloudify.relationships.depends_on
      target: security_group_rules
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }

  cloudify_host:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      agent_config:
        install_method: none
      resource_config:
        kwargs:
          MinCount: 1
          MaxCount: 1
          ImageId: { get_input: ami }
          InstanceType: { get_input: instance_type }
          BlockDeviceMappings:
          - DeviceName: '/dev/sda1'
            Ebs:
              DeleteOnTermination: True
          Placement:
            AvailabilityZone: { get_input: availability_zone }
          UserData: { get_attribute: [ cloudify_host_cloud_config, cloud_config ] }
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.depends_on
        target: cloudify_host_cloud_config
      - type: cloudify.relationships.depends_on
        target: nic1
      - type: cloudify.relationships.depends_on
        target: nic2
      - type: cloudify.relationships.depends_on
        target: centos_core_ami              
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }
```

**Comment by rbk1001** [comment]
Thanks I will try it later

**Comment by rbk1001** [comment]
one question, I have installed the new plugins in cloudify, should I need to change the imports section if I am using the latest awssdk 2.1.1? 

imports:
  - http://www.getcloudify.org/spec/cloudify/4.3/types.yaml
  - http://www.getcloudify.org/spec/awssdk-plugin/2.0.0/plugin.yaml
  - http://www.getcloudify.org/spec/utilities-plugin/1.5.0.1/plugin.yaml
  - http://www.getcloudify.org/spec/fabric-plugin/1.5.1/plugin.yaml
  - imports/manager-configuration.yaml

**Comment by rbk1001** [comment]
I am able to create the 2nd interfaces, but the EC2 instance never able to access. will it due to multiple default gateway created in the instance? anyway to disable the 2nd default route thru plugins configuration?

**Comment by EarthmanT** [comment]
Yes. That is correct. If you are using Cloudify 4.3, there is an alternative plugin import method that you can read about [here](http://docs.getcloudify.org/4.3.0/blueprints/spec-imports/#importing-plugins) that is more flexible regarding plugin versions.

**Comment by rbk1001** [comment]
Hi EarthmanT

can you help on this? "I am able to create the 2nd interfaces, but the EC2 instance never able to access. will it due to multiple default gateway created in the instance? anyway to disable the 2nd default route thru plugins configuration?"

**Comment by EarthmanT** [comment]
I'm not sure the exact routing you need for your exact scenario.

There is already routing in the blueprint for all VMs to reach each other on these two subnets, following [this specification](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html).

Is there a reason that you need the Cloudify Manager to have these two nics, one one the private subnet and one on the public subnet?

**Comment by rbk1001** [comment]
the actual setup that we want to achieve is to have
- one nic served for remote access purpose. so we will need one Elastic IP address and internet gateway for this.
- another nic served for other purpose, wither used for internal EC2 instances connection or even used for VPC peering.

From the lastest awssdk, multiple nics can be created in the EC2 instance, but I am not able to access it. so, I am not sure where is going wrong. is there any suggestion on how to troubleshoot it? or is it really have two default gateways being added inside the EC2 instance?

**Comment by rbk1001** [comment]
I actually got this

# ssh -i "test2.pem" ec2-user@52.76.227.9
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

sounds like the user is wrong, but I have verified the key is correct.

**Comment by rbk1001** [comment]
I think the problem on login is not related to network configuration. it is related to the orginial env setup

is it possible to describe what is required to config in order to allow to login using ec2-user?

**Comment by rbk1001** [comment]
Hi

Understood that multiple nic is able to create now, but is there anyway to hardcode which NIC to which subnet?

in my case, I need to make sure the 1st nic (eth0) land on public_subnet. is there anyway to define it?

**Comment by EarthmanT** [comment]
Hi, in the blueprint, the network is specified to the nic in `SubnetId: { get_attribute: [ public_subnet, aws_resource_id] }`:

```
  nic1:
    type: cloudify.nodes.aws.ec2.Interface
    properties:
      client_config: *client_config
      resource_config:
        kwargs:
          Description: Created by hello-world-blueprint aws-blueprint.yaml.
          SubnetId: { get_attribute: [ public_subnet, aws_resource_id] }
          Groups:
          - { get_attribute: [ security_group, aws_resource_id ] }
    relationships:
    - type: cloudify.relationships.depends_on
      target: public_subnet
    - type: cloudify.relationships.depends_on
      target: security_group
    - type: cloudify.relationships.depends_on
      target: security_group_rules
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }
```

The NIC ordering is per the ordering in the relationships.
