### ISSUE TITLE
Question on VPC Peering (requester)

### ISSUE THREAD

**Issue by rbk1001** [cloudify-incubator/cloudify-awssdk-plugin#120]
Hi 

I would like to create VPC peering with other AWS account, by looking at the sample stated in https://github.com/cloudify-incubator/cloudify-awssdk-plugin/tree/master/examples/ec2-vpc-feature-demo, it looks different compared with the step created in AWS console.

In AWS console, we (VPC requester) will need to input 
1. our own vpc-id
2.  adjacent accounting ID (assumed it is not own account)
3. adjacent regions
4. adjacent vpc-id
5. need to add a new route in the routing table.

How can we make use of the AWSSDK to achieve above? Below is the snapshot of the sample that related to VPC peering from the sample mentioned in above link

```
  vpc_requester:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              CidrBlock: '172.33.0.0/16'


  vpc_accepter:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              CidrBlock: '10.10.0.0/16'

  # Peering Between Two VPC (Requester And Accepter)
  vpc_peering:
    type: cloudify.nodes.aws.ec2.VpcPeering
    properties:
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              PeerVpcId: { get_attribute: [vpc_requester, aws_resource_id] }
              VpcId: { get_attribute: [vpc_accepter, aws_resource_id] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: vpc_accepter
      - type: cloudify.relationships.depends_on
        target: vpc_requester
```

**Comment by EarthmanT** [comment]
Yes.

**Comment by rbk1001** [comment]
I need help on resolve below error

Unknown inputs ['password'] specified - expected inputs: ['as_aws_secret_access_key', 'as_aws_access_key_id', 'availability_zone', 'ec2_region_name', 'as_aws_region_name', 'as_account_id', 'aws_secret_access_key', 'ec2_region_endpoint', 'aws_access_key_id']


below is the yaml

tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.3/types.yaml
  - http://www.getcloudify.org/spec/awssdk-plugin/2.1.1/plugin.yaml
  - http://www.getcloudify.org/spec/utilities-plugin/1.5.0.1/plugin.yaml
  - http://www.getcloudify.org/spec/fabric-plugin/1.5.1/plugin.yaml

inputs:

  aws_access_key_id:
    description: YOUR AWS ACCESS KEY ID

  aws_secret_access_key:
    description: YOUR AWS SECRET ACCESS KEY

  as_aws_access_key_id:
    description: AS AWS ACCESS KEY ID

  as_aws_secret_access_key:
    description: AS AWS SECRET ACCESS KEY

  ec2_region_name:
    default: ap-southeast-1

  as_aws_region_name:
    default: AS REGIONAL NAME

  ec2_region_endpoint:
    default: ec2.ap-southeast-1.amazonaws.com

  availability_zone:
    default: ap-southeast-1c


  as_account_id:
    description: AS ACCOUNT ID


dsl_definitions:

  client_config: &client_config
    aws_access_key_id: { get_input: aws_access_key_id }
    aws_secret_access_key: { get_input: aws_secret_access_key }
    region_name: { get_input: ec2_region_name }

  client_config: &as_client_config
    aws_access_key_id: { get_input: as_aws_access_key_id }
    aws_secret_access_key: { get_input: as_aws_secret_access_key }
    region_name: { get_input: as_aws_region_name }


node_templates:

  vpc_requester:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      use_external_resource: true
      resource_id: vpc-xxxxx
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              CidrBlock: '172.33.11.0/24'


  vpc_accepter:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      use_external_resource: true
      resource_id: vpc-yyyyyyy
      client_config: *as_client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              CidrBlock: '10.10.10.0/24'


  vpc_peering:
    type: cloudify.nodes.aws.ec2.VpcPeering
    properties:
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              PeerOwnerId: { get_input: as_account_id }
              PeerVpcId: { get_attribute: [vpc_requester, aws_resource_id] }
              VpcId: { get_attribute: [vpc_accepter, aws_resource_id] }
              PeerRegion: { get_input: as_aws_region_name }
    relationships:
      - type: cloudify.relationships.depends_on
        target: vpc_accepter
      - type: cloudify.relationships.depends_on
        target: vpc_requester

**Comment by rbk1001** [comment]
Need help. any idea on this?

2018-04-25 13:22:21.374  CFY <cloudify-environment-setup-latest> [vpc_peering_eulvvz.configure] Task started 'cloudify_awssdk.ec2.resources.vpc_peering.create'
2018-04-25 13:22:21.436  CFY <cloudify-environment-setup-latest> [vpc_peering_eulvvz.configure] Task failed 'cloudify_awssdk.ec2.resources.vpc_peering.create' -> Parameter validation failed:
Invalid type for parameter PeerOwnerId, value: 244478496070, type: <type 'int'>, valid types: <type 'basestring'>
2018-04-25 13:22:51.447  CFY <cloudify-environment-setup-latest> [vpc_peering_eulvvz.configure] Sending task 'cloudify_awssdk.ec2.resources.vpc_peering.create' [retry 1/1]
2018-04-25 13:22:51.474  CFY <cloudify-environment-setup-latest> [vpc_peering_eulvvz.configure] Task started 'cloudify_awssdk.ec2.resources.vpc_peering.create' [retry 1/1]
2018-04-25 13:22:51.549  CFY <cloudify-environment-setup-latest> [vpc_peering_eulvvz.configure] Task failed 'cloudify_awssdk.ec2.resources.vpc_peering.create' -> Parameter validation failed:
Invalid type for parameter PeerOwnerId, value: 244478496070, type: <type 'int'>, valid types: <type 'basestring'> [retry 1/1]
2018-04-25 13:22:51.664  CFY <cloudify-environment-setup-latest> 'install' workflow execution failed: Workflow failed: Task failed 'cloudify_awssdk.ec2.resources.vpc_peering.create' -> Parameter validation failed:
Invalid type for parameter PeerOwnerId, value: 1111111111, type: <type 'int'>, valid types: <type 'basestring'>
Workflow failed: Task failed 'cloudify_awssdk.ec2.resources.vpc_peering.create' -> Parameter validation failed:
Invalid type for parameter PeerOwnerId, value: 1111111111, type: <type 'int'>, valid types: <type 'basestring'>

**Comment by rbk1001** [comment]
resolved by add "'" before and after the value, is there anyway to mark the input parameter as a string instead of interger?

**Comment by rbk1001** [comment]
when create a route on vpc_requester, it is failed. A route should be added after VPC peering is created, is there anyway to know the VPC Peering Connection ID, (e.g. pcx-659xxxxx)? how to setup the config in the blueprint?

2018-04-27 07:58:20.827  CFY <cloudify-environment-setup-latest> [route_vpc_requester_5h1ej0.configure] Task failed 'cloudify_awssdk.ec2.resources.route.create' -> An error occurred (MissingParameter) when calling the CreateRoute operation: The request must contain exactly one of gatewayId, natGatewayId, networkInterfaceId, vpcPeeringConnectionId, egressOnlyInternetGatewayId or instanceId



  vpc_requester:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      use_external_resource: true
      resource_id: vpc-xxxxxxxx
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              CidrBlock: '172.32.21.0/28'


  vpc_accepter:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      use_external_resource: true
      resource_id: vpc-yyyyyyyy
      client_config: *as_client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:

          inputs:
            resource_config:
              CidrBlock: '10.10.10.0/24'


  vpc_peering:
    type: cloudify.nodes.aws.ec2.VpcPeering
    properties:
      client_config: *client_config
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              PeerOwnerId: { get_input: as_account_id }
              PeerVpcId: { get_attribute: [vpc_accepter, aws_resource_id] }
              VpcId: { get_attribute: [vpc_requester, aws_resource_id] }
              PeerRegion: { get_input: as_aws_region_name }
    relationships:
      - type: cloudify.relationships.depends_on
        target: vpc_accepter
      - type: cloudify.relationships.depends_on
        target: vpc_requester

  route_vpc_requester:
    type: cloudify.nodes.aws.ec2.Route
    properties:
      resource_config:
        kwargs:
          DestinationCidrBlock: '0.0.0.0/0'
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.contained_in
        target: route_table_vpc_requester


  route_table_vpc_requester:
    type: cloudify.nodes.aws.ec2.RouteTable
    properties:
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.contained_in
        target: vpc_requester
      - type: cloudify.relationships.connected_to
        target: private_subnet

**Comment by EarthmanT** [comment]
Check which attributes have been assigned for the resource on the CLI
`cfy node-instances` and add the appropriate key and value to the operation kwargs.

```
  route_vpc_requester:
    type: cloudify.nodes.aws.ec2.Route
    properties:
      resource_config:
        kwargs:
          DestinationCidrBlock: '0.0.0.0/0'
          vpcPeeringConnectionId: { get_attribute: [ your_vpc_peering_connection, aws_resource_id ] }
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.contained_in
        target: route_table_vpc_requester

```
