### ISSUE TITLE
Wrong Interface ordering

### ISSUE THREAD

**Issue by rbk1001** [cloudify-incubator/cloudify-awssdk-plugin#121]
Hi

During the testing on multiple interfaces on the instance creation, it is found that the interface is not in order occasionally.

this is the assigned found in the AWS console.

  

Network Interface eth0
================
Interface IDeni-28b1cxxx
VPC IDvpc-xxxxxxxxxxx
Attachment Owner --------
Attachment Status attached
Attachment TimeFri Apr 27 11:54:27 GMT+800 2018
Delete on Terminatefalse
Private IP Address172.32.21.14

Below is the blueprints
```
  public_subnet_cidr:
    default: 172.32.11.0/28

  private_subnet_cidr:
    default: 172.32.21.0/28

  public_subnet:
    type: cloudify.nodes.aws.ec2.Subnet
    properties:
      resource_config:
        kwargs:
          CidrBlock: { get_input: public_subnet_cidr }
          AvailabilityZone: { get_input: availability_zone }
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: vpc
    - type: cloudify.relationships.depends_on
      target: internet_gateway

  private_subnet:
    type: cloudify.nodes.aws.ec2.Subnet
    properties:
      resource_config:
        kwargs:
          CidrBlock: { get_input: private_subnet_cidr }
          AvailabilityZone: { get_input: availability_zone }
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: vpc

  nic0:
    type: cloudify.nodes.aws.ec2.Interface
    properties:
      client_config: *client_config
      resource_config:
        kwargs:
          Description: OperA - Management Interface.
          SubnetId: { get_attribute: [ public_subnet, aws_resource_id] }
          Groups:
          - { get_attribute: [ security_group, aws_resource_id ] }
    relationships:
    - type: cloudify.relationships.depends_on
      target: public_subnet
    - type: cloudify.relationships.depends_on
      target: security_group
    - type: cloudify.relationships.depends_on
      target: security_group_rules
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }

  nic1:
    type: cloudify.nodes.aws.ec2.Interface
    properties:
      client_config: *client_config
      resource_config:
        kwargs:
          Description: Internal
          SubnetId: { get_attribute: [ private_subnet, aws_resource_id] }
          Groups:
          - { get_attribute: [ security_group_gn, aws_resource_id ] }
    relationships:
    - type: cloudify.relationships.depends_on
      target: private_subnet
    - type: cloudify.relationships.depends_on
      target: security_group_gn
    - type: cloudify.relationships.depends_on
      target: security_group_rules_gn
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }

 cloudify_host:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      agent_config:
        install_method: none
      resource_config:
        kwargs:
          MinCount: 1
          MaxCount: 1
          ImageId: { get_input: ami }
          InstanceType: { get_input: instance_type }
          KeyName: { get_input: key_name }
          BlockDeviceMappings:
          - DeviceName: '/dev/sda1'
            Ebs:
              DeleteOnTermination: True
          Placement:
            AvailabilityZone: { get_input: availability_zone }
          UserData: { get_attribute: [ cloudify_host_cloud_config, cloud_config ] }
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.depends_on
        target: cloudify_host_cloud_config
      - type: cloudify.relationships.depends_on
        target: nic0
      - type: cloudify.relationships.depends_on
        target: nic1
      - type: cloudify.relationships.depends_on
        target: ami
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          inputs:
            resource_config: { get_property: [ SELF, resource_config, kwargs] }
```

**Comment by EarthmanT** [comment]
The best way to do what you want to do is the be explicit about the nic device index assignment:

```
 cloudify_host:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      agent_config:
        install_method: none
      resource_config:
        kwargs:
          MinCount: 1
          MaxCount: 1
          ImageId: { get_input: ami }
          InstanceType: { get_input: instance_type }
          KeyName: { get_input: key_name }
          BlockDeviceMappings:
          - DeviceName: '/dev/sda1'
            Ebs:
              DeleteOnTermination: True
          Placement:
            AvailabilityZone: { get_input: availability_zone }
          UserData: { get_attribute: [ cloudify_host_cloud_config, cloud_config ] }
          NetworkInterfaces:
          - NetworkInterfaceId: { get_attribute: [ nic0, aws_resource_id ] }
             DeviceIndex: 0
          - NetworkInterfaceId: { get_attribute: [ nic1, aws_resource_id ] }
             DeviceIndex: 1
      client_config: *client_config
```
