### ISSUE TITLE
Problem on the type of VpcPeeringConnectionId

### ISSUE THREAD

**Issue by rbk1001** [cloudify-incubator/cloudify-awssdk-plugin#123]
How should I define the type for VpcPeeringConnectionId?

error
-----
[route_vpc_requester_nagcrj.configure] Task started 'cloudify_awssdk.ec2.resources.route.create'
2018-04-30 04:35:37.007  CFY <cloudify-environment-setup-latest> [route_vpc_requester_nagcrj.configure] Task failed 'cloudify_awssdk.ec2.resources.route.create' -> Parameter validation failed:
Invalid type for parameter VpcPeeringConnectionId, value: {u'get_attribute': [u'vpc_peering', u'aws_resource_id']}, type: <type 'dict'>, valid types: <type 'basestring'>

blueprint
-----------
```
  route_vpc_requester:
    type: cloudify.nodes.aws.ec2.Route
    properties:
      resource_config:
        kwargs:
          DestinationCidrBlock: '0.0.0.0/0'
          VpcPeeringConnectionId: { get_attribute: [ vpc_peering, aws_resource_id ] }
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.contained_in
      target: route_table_vpc_requester
    - type: cloudify.relationships.depends_on
      target: vpc_peering

```

**Comment by EarthmanT** [comment]
Hi
If you are executing a blueprint in a local profile you need to put the kwargs section in the inputs to the operation like this:
```
  route_vpc_requester:
    type: cloudify.nodes.aws.ec2.Route
    properties:
      resource_config:
        kwargs:
          DestinationCidrBlock: '0.0.0.0/0'
          VpcPeeringConnectionId: { get_attribute: [ vpc_peering, aws_resource_id ] }
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.contained_in
      target: route_table_vpc_requester
    - type: cloudify.relationships.depends_on
      target: vpc_peering
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          inputs:
            resource_config:
              DestinationCidrBlock: '0.0.0.0/0'
              VpcPeeringConnectionId: { get_attribute: [ vpc_peering, aws_resource_id ] }
```
