### ISSUE TITLE
How we can add name to an instance in the aws.ec2.Instances?

### ISSUE THREAD

**Issue by rbk1001** [cloudify-incubator/cloudify-awssdk-plugin#124]
```
  cloudify_host:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      agent_config:
        install_method: none
      resource_config:
        kwargs:
          MinCount: 1
          MaxCount: 1
          ImageId: { get_input: ami }
          InstanceType: { get_input: instance_type }
          KeyName: { get_input: key_name }
          BlockDeviceMappings:
          - DeviceName: '/dev/sda1'
```

**Comment by EarthmanT** [comment]
Use the tags type:

example:

```
  cloudify_host:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      agent_config:
        install_method: none
      resource_config:
        kwargs:
          MinCount: 1
          MaxCount: 1
          ImageId: { get_input: ami }
          InstanceType: { get_input: instance_type }
          KeyName: { get_input: key_name }
          BlockDeviceMappings:
          - DeviceName: '/dev/sda1'

  cloudify_host_tag:
    type: cloudify.nodes.aws.ec2.Tags
    properties:
      resource_config:
        kwargs:
          Tags:
          - Key: Name
            Value: Hello-See-My-Name
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: cloudify_host
```
