### ISSUE TITLE
EC2VPNConnection creation and deletion fails when workflow for a single deployment executed several times

### ISSUE THREAD

**Issue by dandrushko** [cloudify-incubator/cloudify-awssdk-plugin#131]
VPNConnection fails during creation/deletion when appropriate workflow executed for a single deployment executed several times. Steps to reproduce:
1) Create sample blueprint which creates customer GW, VPN GW and VPN connection, like

```
node_templates:

 exists_vpc:
   type: cloudify.nodes.aws.ec2.Vpc
   properties:
     client_config: *aws_config
     use_external_resource: true
     resource_id: { get_input: aws_vpc_id}

 vpn_gateway_one:
    type: cloudify.nodes.aws.ec2.VPNGateway
    properties:
      resource_config:
        kwargs:
          Type: 'ipsec.1'
      client_config: *aws_config
    relationships:
      - type: cloudify.relationships.connected_to
        target: exists_vpc

 customer_gateway_one:
   type: cloudify.nodes.aws.ec2.CustomerGateway
   properties:
     resource_config:
       kwargs:
         Type: 'ipsec.1'
         PublicIp: { get_input: openstack_public_ip}
         BgpAsn: 65000
     client_config: *aws_config

 vpn_connection_vpc_requster:
   type: cloudify.nodes.aws.ec2.VPNConnection
   properties:
     client_config: *aws_config
   interfaces:
     cloudify.interfaces.lifecycle:
        create:
          inputs:
            resource_config:
              CustomerGatewayId: { get_attribute: [customer_gateway_one, aws_resource_id] }
              Type: 'ipsec.1'
              VpnGatewayId: { get_attribute: [vpn_gateway_one, aws_resource_id] }
              Options:
                StaticRoutesOnly: False
   relationships:
     - type: cloudify.relationships.depends_on
       target: vpn_gateway_one
     - type: cloudify.relationships.depends_on
       target: customer_gateway_one
```

2. Execute install/uninstall workflow several times, sample test is
`  def test_blueprint(self, cfy_local):
        cfy_local.execute('install', task_retries=1)
        cfy_local.execute('uninstall', task_retries=1)
        cfy_local.execute('install', task_retries=1)
        cfy_local.execute('uninstall', task_retries=1)
`
**Expected result**: service installed->uninstalled->installed->uninstalled
**Actual result**: service installed->uninstalled-> Error
or 
service installed->uninstalled->installed->Error
