### ISSUE TITLE
IAM User PasswordPolicy

### ISSUE THREAD

**Issue by 01000101** [cloudify-incubator/cloudify-awssdk-plugin#81]
Please implement a type for this: http://boto3.readthedocs.io/en/latest/reference/services/iam.html#accountpasswordpolicy to set account password policies.

**Comment by EarthmanT** [comment]
What lifecycle operations do you need? 

The `iam.accountpasswordpolicy` resource manages the global account policy. Why would want Cloudify to manage the policy for the entire account? If you want to create a custom password policy for users you can already do that with `cloudify.nodes.aws.iam.Policy` doing something like this

```
  someuser_get_change_password_policy:
    type: cloudify.nodes.aws.iam.Policy
    relationships:
    - type: cloudify.relationships.depends_on
      target: someuser
    properties:
      client_config: *client_config
      resource_config:
        kwargs:
          Description: Allows someuser to change password.
          Path: !!str /someuser-getchange-password-policy/
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iam:GetAccountPasswordPolicy
              Resource: "*"
            - Effect: Allow
              Action:
              - iam:ChangePassword
              Resource:
                concat:
                - "arn:aws:iam::*:user/"
                - { get_property: someuser, resource_id }

```
